// Generated by CoffeeScript 1.6.2
(function() {
	$(function() {
		var data, i, input, inputs, key, name, saved, savedData, savedInputs, savedSelects, savedTexts, select, selects, textarea, texts, url, val, _i, _j, _len, _len1, _ref, _ref1, _ref2, _results;

		url = window.location.pathname;

		var key = prompt("Enter the name under which the form was saved", "Default");
		if (key == null) {
			return;
		}

		data = localStorage.getItem(key);
		if (!data) {
			alert('Not found');
			return;
		}
		savedData = JSON.parse(data);

		_ref = $('input');
		for (_i = 0, _len = _ref.length; _i < _len; _i++) {
			input = _ref[_i];
			if (!$(input).is(':visible')) {
				continue;
			}

			console.log('some this[' + _i + ']: ' + input.name + ' = ' + input.value);

			input.value = savedData[_i];
		}

		return;
	});

}).call(this);
