// Generated by CoffeeScript 1.6.2
(function() {
	$(function() {
		inputs = {};
		_ref = $('input');
		for (_i = 0, _len = _ref.length; _i < _len; _i++) {
			input = _ref[_i];
			if (!$(input).is(':visible')) {
				continue;
			}

			console.log('some this[' + _i + ']: ' + input.name + ' = ' + input.value);

			inputs[_i] = input.value;
		}

		var key = prompt("Enter the name under which to save the form", "Default");
		if (key == null) {  
			return;
		}

		return localStorage.setItem(key, JSON.stringify(inputs));
	});

}).call(this);
